# config/zed2i_imu_only.yaml
# Configuração ZED2i IMU-ONLY - Sem GPU, apenas sensores inerciais
---
/**:
    ros__parameters:
        # === CONFIGURAÇÃO GERAL ===
        general:
            camera_model: 'zed2i'
            camera_name: 'zed'
            grab_resolution: 'VGA'          # Mínima resolução para economia
            grab_frame_rate: 30             # Frame rate mínimo
            pub_frame_rate: 1.0             # Publicação mínima (não usamos imagem)
            gpu_id: -1                      # FORÇAR CPU-only mode
            sn: 0                           # Auto-detect serial number
            verbose: false                  # Logs mínimos
            opencv_calibration_file: ''     # Sem calibração extra
            self_calib: true                # Auto-calibração ativada
            camera_flip: false              # Sem flip
            camera_timeout_sec: 5           # Timeout para conexão
            max_reconnect_temp: 5           # Tentativas de reconexão
            
        # === VÍDEO DESABILITADO ===
        video:
            brightness: 4
            contrast: 4  
            hue: 0
            saturation: 4
            sharpness: 4
            gamma: 8
            auto_exposure_gain: true
            exposure: 80
            gain: 80
            auto_whitebalance: true
            whitebalance_temperature: 42
            
        # === DEPTH TOTALMENTE DESABILITADO ===
        depth:
            quality: 1                      # Qualidade mínima (não usado)
            sensing_mode: 0                 # STANDARD (não usado)
            depth_stabilization: 1          # Mínimo (não usado)
            openni_depth_mode: false        # Desabilitado
            depth_downsample_factor: 1      # Sem downsample
            min_depth: 0.3                  # Não usado
            max_depth: 1.0                  # Mínimo (não usado)
            depth_confidence: 50            # Não usado
            depth_texture_confidence: 100   # Não usado
            remove_saturated_areas: true    # Não usado
            
        # === POS TRACKING DESABILITADO ===
        pos_tracking:
            pos_tracking_enabled: false     # SEM SLAM interno ZED
            publish_tf: false               # NÃO publicar odometria ZED
            publish_map_tf: false           # NÃO publicar map transform
            map_frame: 'map'                # Frame padrão (não usado)
            odometry_frame: 'odom'          # Frame padrão (não usado)
            area_memory_db_path: ''         # Sem banco de dados
            save_area_memory_db_on_exit: false
            area_memory: true
            imu_fusion: false               # SEM fusão IMU interna (faremos externa)
            floor_alignment: false          # Sem alinhamento ao chão
            initial_base_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # Pose inicial
            init_odom_with_first_valid_pose: true
            path_pub_rate: 2.0              # Taxa de publicação path (não usado)
            path_max_count: -1              # Máximo de pontos path
            two_d_mode: false               # Modo 3D (não usado)
            fixed_z_value: 0.00             # Z fixo para 2D
            predict_to_camera_time: true    # Predição temporal
            transform_time_offset: 0.0      # Offset temporal
            depth_min_range: 0.0            # Range mínimo depth
            set_gravity_as_origin: true     # Gravidade como origem
            set_floor_as_origin: false      # Sem chão como origem
            
        # === SENSORES IMU HABILITADOS ===
        sensors:
            sensors_image_sync: false       # SEM sync com imagem
            sensors_pub_rate: 200.0         # IMU a 200Hz - MÁXIMA PRECISÃO
            publish_imu_tf: true            # Publicar TF do IMU
            
        # === MAPPING DESABILITADO ===
        mapping:
            mapping_enabled: false          # SEM mapping interno
            resolution: 0.05                # Não usado
            max_mapping_range: -1           # Não usado
            fused_pointcloud_freq: 1.0      # Não usado
            clicked_point_topic: '/clicked_point' # Não usado
            
        # === OBJECT DETECTION DESABILITADO ===
        object_detection:
            od_enabled: false               # SEM object detection
            allow_reduced_precision_inference: false
            max_range: 20.0                 # Não usado
            prediction_timeout: 2.0         # Não usado
            filtering_mode: 1               # Não usado
            mc_people: true                 # Não usado
            mc_vehicle: true                # Não usado
            mc_bag: true                    # Não usado
            mc_animal: true                 # Não usado
            mc_electronics: true            # Não usado
            mc_fruit_vegetable: true        # Não usado
            mc_sport: true                  # Não usado
            
        # === BODY TRACKING DESABILITADO ===  
        body_tracking:
            bt_enabled: false               # SEM body tracking
            model: 2                        # Não usado
            allow_reduced_precision_inference: false
            max_range: 20.0                 # Não usado
            prediction_timeout: 0.5         # Não usado
            fitting: false                  # Não usado
            body_kp_selection: 0            # Não usado
            enable_body_fitting: false     # Não usado
            enable_tracking: true           # Não usado
            
        # === OUTROS RECURSOS DESABILITADOS ===
        region_of_interest:
            automatic_roi: false            # ROI desabilitado
            depth_far_threshold_meters: 2.5 # Não usado
            image_height_ratio_cutoff: 0.5  # Não usado
