controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: forward_command_controller/ForwardCommandController
      joints:
        - front_left_wheel_joint
        - front_right_wheel_joint
        - rear_left_wheel_joint
        - rear_right_wheel_joint
      interface_name: velocity
