controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

mecanum_drive_controller:
  ros__parameters:
    use_sim_time: true
    
    # Joint names (YouBot SDF model)
    front_left_joint_name: "wheel_joint_fl"
    front_right_joint_name: "wheel_joint_fr"
    back_left_joint_name: "wheel_joint_bl"
    back_right_joint_name: "wheel_joint_br"
    
    # Robot dimensions (YouBot Kuka specifications)
    wheel_base: 0.470          # Distance between front and back wheels [m]
    wheel_separation: 0.370    # Distance between left and right wheels [m]
    wheel_radius: 0.05         # Wheel radius [m]
    
    # Multiplicadores para compensar a falta de geometria mecanum real
    wheel_separation_multiplier: 1.2  # Compensação para movimento lateral
    front_left_wheel_radius_multiplier: 1.0
    front_right_wheel_radius_multiplier: 1.0
    back_left_wheel_radius_multiplier: 1.0
    back_right_wheel_radius_multiplier: 1.0
    
    # Frame IDs
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    
    # Publishing
    enable_odom_tf: true
    publish_limited_velocity: false
    velocity_rolling_window_size: 10
    use_stamped_vel: true
    
    # Timeout
    cmd_vel_timeout: 0.5
    
    # Covariance
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
