controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

mecanum_controller:
  ros__parameters:
    # Nomes dos joints (iguais ao Yahboom)
    front_left_joint_name: front_left_wheel_joint
    front_right_joint_name: front_right_wheel_joint
    back_left_joint_name: back_left_wheel_joint
    back_right_joint_name: back_right_wheel_joint

    # Parâmetros físicos do robô (ajuste conforme seu modelo real)
    wheel_base: 0.16
    wheel_separation: 0.169
    wheel_radius: 0.0325
    wheel_separation_multiplier: 1.0
    front_left_wheel_radius_multiplier: 1.0
    front_right_wheel_radius_multiplier: 1.0
    back_left_wheel_radius_multiplier: 1.0
    back_right_wheel_radius_multiplier: 1.0

    # Frames
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true

    # Odometry
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    position_feedback: true
    open_loop: false

    # Comando
    cmd_vel_timeout: 0.5
    publish_limited_velocity: false
    velocity_rolling_window_size: 10
    publish_rate: 50.0

    # Limites de velocidade (ajuste se necessário)
    linear.x.has_velocity_limits: false
    linear.y.has_velocity_limits: false
    angular.z.has_velocity_limits: false
