controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false

mecanum_drive_controller:
  ros__parameters:
    use_sim_time: false
    
    # Joint names (nomes corretos do URDF do robô Caramelo)
    front_left_joint_name: "front_left_wheel_joint"
    front_right_joint_name: "front_right_wheel_joint"
    back_left_joint_name: "back_left_wheel_joint"
    back_right_joint_name: "back_right_wheel_joint"
    
    # Robot dimensions (dimensões corretas do URDF do robô Caramelo)
    wheel_base: 0.470          # Distance between front and back wheels [m] - do URDF
    wheel_separation: 0.310    # Distance between left and right wheels [m] - do URDF  
    wheel_radius: 0.05         # Wheel radius [m] - do URDF (5cm)
    
    # Multiplicadores para compensar características mecânicas
    wheel_separation_multiplier: 1.0
    front_left_wheel_radius_multiplier: 1.0
    front_right_wheel_radius_multiplier: 1.0
    back_left_wheel_radius_multiplier: 1.0
    back_right_wheel_radius_multiplier: 1.0
    
    # Frame IDs (corretos conforme padrão ROS2)
    base_frame_id: "base_footprint"    # Frame padrão para navegação
    odom_frame_id: "odom"
    
    # Publishing settings
    enable_odom_tf: true
    publish_limited_velocity: false
    velocity_rolling_window_size: 10
    use_stamped_vel: false             # Mudado para false (padrão)
    
    # Timeout
    cmd_vel_timeout: 0.5
    
    # Speed limits (limites conservadores para robô real)
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.8   # m/s - aumentado um pouco
        min_velocity: -0.8
        has_acceleration_limits: true
        max_acceleration: 1.0  # m/s^2 
        min_acceleration: -1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.5   # rad/s - aumentado um pouco
        min_velocity: -1.5
        has_acceleration_limits: true
        max_acceleration: 2.0  # rad/s^2
        min_acceleration: -2.0
    
    # Covariance matrices (valores mais apropriados)
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
