# Nav2 - Configuração SIMPLES para robô real
# Caramelo - Sistema de navegação autônoma

# AMCL - Localização ROBUSTA para Competição (Encoder + LiDAR híbrido)
amcl:
  ros__parameters:
    use_sim_time: false
    # === 🎯 OTIMIZAÇÃO ESPECÍFICA PARA ROTAÇÃO IMPRECISA ===
    # LiDAR para correção angular, encoder para posição X/Y
    alpha1: 0.4   # ⭐ AUMENTADO MAIS - rotação do encoder tem alta incerteza
    alpha2: 0.2   # ⭐ MODERADO - ruído translacional por rotação 
    alpha3: 0.05  # ⭐ MUITO BAIXO - encoder X/Y é confiável
    alpha4: 0.3   # ⭐ ALTO - rotação por translação também imprecisa
    alpha5: 0.15  # ⭐ MODERADO - ruído geral para permitir correções do LiDAR
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1   # ⭐ REDUZIDO - dar mais peso a leituras curtas (detecção precisa)
    laser_likelihood_max_dist: 1.5  # ⭐ AUMENTADO - considera matches mais distantes
    laser_max_range: 10.0  # ⭐ AUMENTADO - usa alcance completo do LiDAR
    laser_min_range: 0.1   
    laser_model_type: "likelihood_field"
    max_beams: 60    # ⭐ AUMENTADO - mais beams para correção rotacional
    max_particles: 2000  # ⭐ AUMENTADO - mais partículas para melhor localização
    min_particles: 500   # ⭐ AUMENTADO - base maior para robustez
    odom_frame_id: "odom"
    pf_err: 0.05  # ⭐ RELAXADO - permite mais correção pelo LiDAR
    pf_z: 0.95    # ⭐ REDUZIDO - menos confiança para permitir correções
    recovery_alpha_fast: 0.2   # ⭐ MAIS RÁPIDO - recuperação ativa
    recovery_alpha_slow: 0.001 # ⭐ LENTO para evitar saltos
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"  # ⭐ OMNI MODEL para mecanum!
    save_pose_rate: 5.0  # ⭐ AUMENTADO para salvar pose mais frequentemente
    sigma_hit: 0.2  # ⭐ REDUZIDO - mais exigente com matches para precisão
    tf_broadcast: true
    transform_tolerance: 2.0  # ⭐ REDUZIDO para melhor sincronização
    update_min_a: 0.1   # ⭐ MAIS FREQUENTE - update a cada 6° (melhor correção rotacional)
    update_min_d: 0.05  # ⭐ MAIS FREQUENTE - update a cada 5cm (melhor precisão)
    
    # === 🎯 CONFIGURAÇÃO HÍBRIDA: ENCODER (X/Y) + LIDAR (ROTAÇÃO) ===
    # Usar encoder para posição, LiDAR para corrigir orientação
    global_localization: false  # ⭐ Evitar relocalizações drásticas
    initial_pose_covariance_xx: 0.25      # ⭐ REDUZIDA - confiança alta em X (encoder bom)
    initial_pose_covariance_yy: 0.25      # ⭐ REDUZIDA - confiança alta em Y (encoder bom)  
    initial_pose_covariance_aa: 0.68      # ⭐ AUMENTADA - menos confiança em rotação (39°)
    
    # === PESO OTIMIZADO: LiDAR dominante para correção angular ===
    z_hit: 0.95   # ⭐ MÁXIMO peso aos hits do LIDAR (crucial para orientação)
    z_max: 0.025  # ⭐ MÍNIMO peso para leituras no limite
    z_rand: 0.025 # ⭐ MÍNIMO peso para ruído aleatório
    z_short: 0.0  # ⭐ ZERO peso para leituras curtas
    scan_topic: scan
    map_topic: map
    
    # === SINCRONIZAÇÃO OTIMIZADA ===
    tf_tolerance: 0.5                    # ⭐ REDUZIDA para sincronização precisa
    laser_max_beams: 180                 # ⭐ AUMENTADO - usar mais dados do LiDAR
    laser_z_hit: 0.95                    # ⭐ MUITO ALTO - priorizar dados do LiDAR
    laser_z_rand: 0.05                   # ⭐ BAIXO ruído aleatório
    laser_sigma_hit: 0.1                 # ⭐ Alta precisão do LIDAR
    
    set_initial_pose: true
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

# Behavior Tree Navigator
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"

# Controller Server - DWB para Mecanum Drive Holonômico
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0  # ⭐ AUMENTADO para controle mais responsivo
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001  # ⭐ REDUZIDO - permite movimento lateral (holonômico)
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] 
    controller_plugins: ["FollowPath"]  # DWB para navegação holonômica
    
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.05  # ⭐ REDUZIDO para WS (movimento mais preciso)
      movement_time_allowance: 30.0   # ⭐ AUMENTADO para manobras complexas em WS
      
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05  # ⭐ MUITO RESTRITIVO para posicionamento preciso em WS
      yaw_goal_tolerance: 0.087  # ⭐ 5° para orientação precisa em WS
      
    # === DWB PLANNER - NAVEGAÇÃO HOLONÔMICA PARA MECANUM ===
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: -0.3  # ⭐ Permite movimento para trás
      min_vel_y: -0.3  # ⭐ Permite movimento lateral (HOLONÔMICO)
      max_vel_x: 0.5   # ⭐ Velocidade máxima frente
      max_vel_y: 0.3   # ⭐ Velocidade lateral para mecanum
      max_vel_theta: 1.0
      min_speed_xy: 0.01  # ⭐ Velocidade mínima para movimento suave
      max_speed_xy: 0.5   # ⭐ Velocidade máxima combinada
      min_speed_theta: 0.05
      acc_lim_x: 0.3      # ⭐ Aceleração suave
      acc_lim_y: 0.3      # ⭐ Aceleração lateral suave  
      acc_lim_theta: 1.5  # ⭐ Aceleração angular
      decel_lim_x: -0.3   # ⭐ Desaceleração
      decel_lim_y: -0.3   # ⭐ Desaceleração lateral
      decel_lim_theta: -1.5
      vx_samples: 5       # ⭐ Amostras de velocidade X
      vy_samples: 5       # ⭐ Amostras de velocidade Y (holonômico)
      vtheta_samples: 10  # ⭐ Amostras de velocidade angular
      sim_time: 2.0       # ⭐ Tempo de simulação para trajetórias
      sim_granularity: 0.05 # ⭐ Granularidade da simulação
      sim_period: 0.1     # ⭐ Período de simulação
      discretize_by_time: false
      angular_sim_granularity: 0.1
      transform_tolerance: 0.5
      
      # === CRITICS (Avaliadores de Trajetória) ===
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      
      BaseObstacle:
        scale: 0.02  # ⭐ REDUZIDO - permite passar mais perto de obstáculos quando necessário
        sum_scores: false
        
      PathAlign:
        scale: 32.0
        forward_point_distance: 0.1
        
      PathDist:
        scale: 32.0
        
      GoalAlign:
        scale: 24.0  # ⭐ AUMENTADO - importante para orientação precisa em WS
        forward_point_distance: 0.1
        
      GoalDist:
        scale: 24.0  # ⭐ AUMENTADO - importante para posição precisa em WS
        
      RotateToGoal:
        scale: 32.0
        slowing_factor: 5.0
        lookahead_time: -1.0
        
      Oscillation:
        scale: 1.0
        oscillation_reset_dist: 0.05
        oscillation_reset_angle: 0.2
        oscillation_reset_time: -1.0

# Local Costmap - LiDAR para obstáculos dinâmicos apenas
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0  # ⭐ AUMENTADO para detecção rápida de obstáculos dinâmicos
      publish_frequency: 5.0  # ⭐ AUMENTADO para responsividade
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: false
      rolling_window: true
      width: 4  # ⭐ AUMENTADO para melhor visão de obstáculos
      height: 4 # ⭐ AUMENTADO para melhor visão de obstáculos
      resolution: 0.05
      transform_tolerance: 1.0
      # === FOOTPRINT PRECISO DO CARAMELO (retângulo mais comprido que largo) ===
      footprint: "[[0.185, 0.175], [0.185, -0.175], [-0.185, -0.175], [-0.185, 0.175]]"  # ⭐ 37cm x 35cm
      plugins: ["obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0   # ⭐ AUMENTADO para melhor clearing
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5   # ⭐ AUMENTADO para detecção precoce
          obstacle_min_range: 0.0
          inf_is_valid: false       # ⭐ Ignora leituras infinitas
          clearing_on_max_reading: true  # ⭐ Limpa com leituras máximas
          
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0    # ⭐ REDUZIDO - permite aproximação para WS
        inflation_radius: 0.20      # ⭐ AUMENTADO - margem de segurança maior
        inflate_unknown: false     # ⭐ Não infla áreas desconhecidas
        inflate_around_unknown: true # ⭐ Infla ao redor de desconhecidas
        
      always_send_full_costmap: True

# Global Costmap - Mapa estático + obstáculos dinâmicos (SEM SOBRESCREVER MAPA)
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: false
      # === FOOTPRINT PRECISO DO CARAMELO (retângulo mais comprido que largo) ===
      footprint: "[[0.185, 0.175], [0.185, -0.175], [-0.185, -0.175], [-0.185, 0.175]]"  # ⭐ 37cm x 35cm
      resolution: 0.05
      transform_tolerance: 1.0
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        subscribe_to_updates: false  # ⭐ CRUCIAL: não aceita updates do mapa estático
        
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        combination_method: 1  # ⭐ MAXIMUM: LiDAR só ADICIONA obstáculos, não remove mapa estático
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: False      # ⭐ CRUCIAL: LiDAR NÃO APAGA mapa estático
          marking: True        # ⭐ LiDAR só MARCA novos obstáculos dinâmicos
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          inf_is_valid: false
          expected_update_rate: 10.0  # ⭐ Frequência esperada do LiDAR
          observation_persistence: 2.0 # ⭐ Mantém obstáculos por 2s após sumirem
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_range: 2.5
          raytrace_range: 3.0
          
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0    # ⭐ GLOBAL: penalização padrão
        inflation_radius: 0.15      # ⭐ GLOBAL: 15cm de margem geral
        inflate_unknown: false     # ⭐ Não infla áreas desconhecidas
        inflate_around_unknown: false # ⭐ Não infla ao redor de desconhecidas no global
        
      always_send_full_costmap: True

# Map Server
map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/work/Caramelo_workspace/maps/arena_fei/map.yaml"

# Planner Server - A* para competição
planner_server:
  ros__parameters:
    expected_planner_frequency: 30.0  # ⭐ AUMENTADO para A* mais rápido
    use_sim_time: false
    planner_plugins: ["GridBased"]
    
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.3  # ⭐ REDUZIDO para melhor precisão em WS
      use_astar: true  # ⭐ A* HABILITADO para planejamento mais rápido e eficiente
      allow_unknown: true
      use_final_approach_orientation: true  # ⭐ Manter orientação final (crucial para WS)
      use_quadratic_cost_penalty: false
      use_dijkstra: false  # ⭐ Confirmar que usa A* ao invés de Dijkstra

# Smoother Server - Simplificado para ROS2 Jazzy
smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

# Behavior Server
behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
      
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.3  # AUMENTADO para sincronização
    use_sim_time: false
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

# Waypoint Follower
waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 1
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 0

# Velocity Smoother
velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 1.0]
    min_velocity: [-0.5, 0.0, -1.0]
    max_accel: [0.5, 0.0, 3.2]
    max_decel: [-0.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
