slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping #localization
    
    # CONFIGURAÇÃO HÍBRIDA: Scan matching moderado para alinhamento de paredes
    # mas SEM correção drástica da odometria
    publish_odom_tf: false  # Encoder publica TF odom->base_footprint
    publish_scan_match_odom: false  # NÃO sobrescrever odometria dos encoders
    
    debug_logging: false
    
    # === CONFIGURAÇÕES PARA RPLIDAR S2 ===
    throttle_scans: 1               # Processa TODOS os scans - mais rápido
    transform_publish_period: 0.02  # 50Hz para map->odom transform
    map_update_interval: 0.1        # 10Hz - MUITO RÁPIDO para ver mapa sendo montado
    resolution: 0.015               # 1.5cm por pixel - ALTA RESOLUÇÃO (células menores)
    max_laser_range: 30.0           # 30m - alcance máximo do RPLidar S2
    minimum_time_interval: 0.05     # 50ms - atualização muito rápida
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000
    enable_interactive_mode: true
    
    # === LIMITAÇÃO ANGULAR: 90° A 270° (FRENTE E LATERAIS) ===
    # Ângulos em radianos: 90° = π/2, 270° = 3π/2
    angle_filter_threshold: 1.5708  # π/2 = 90°
    # O SLAM vai usar apenas os dados entre 90° e 270°
    use_response_expansion: true

    # === SCAN MATCHING OTIMIZADO PARA RPLIDAR S2 ===
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2    # 20cm - atualização frequente
    minimum_travel_heading: 0.2     # ~11° - atualização frequente
    scan_buffer_size: 10            # Buffer maior para melhor matching
    scan_buffer_maximum_scan_distance: 30.0  # Alcance máximo RPLidar S2
    link_match_minimum_response_fine: 0.5    # Aceita matches razoáveis
    link_scan_maximum_distance: 1.0          # Correções locais normais
    loop_search_maximum_distance: 3.0        # Loop closure normal
    do_loop_closing: true                    # HABILITADO para melhor mapa
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 0.8
    loop_match_minimum_response_coarse: 0.5
    loop_match_minimum_response_fine: 0.5

    # === PARÂMETROS DE CORRELAÇÃO PARA RPLIDAR S2 ===
    correlation_search_space_dimension: 0.5  # Área de busca normal
    correlation_search_space_resolution: 0.01  # Alta precisão
    correlation_search_space_smear_deviation: 0.1  # Baixa tolerância

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # === PENALIDADES NORMAIS PARA RPLIDAR S2 ===
    distance_variance_penalty: 0.5      # Penalidade baixa - confia no RPLidar S2
    angle_variance_penalty: 1.0         # Penalidade normal    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
