slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping  # ✅ CORRETO: usar mapeamento para criar novo mapa
    
    # CONFIGURAÇÃO PARA MAPEAMENTO: TF odom->base_footprint vem do encoder
    publish_odom_tf: false  # Encoder publica TF odom->base_footprint
    publish_scan_match_odom: false  # Desabilitado - usar apenas odometria do encoder
    
    debug_logging: false
    
    # === CONFIGURAÇÕES PARA RPLIDAR S2 COMO SENSOR DE PROXIMIDADE ===
    throttle_scans: 1               # Processa TODOS os scans - dados brutos
    transform_publish_period: 0.02  # 50Hz para map->odom transform
    map_update_interval: 0.1        # 10Hz - RÁPIDO para ver mapa sendo montado
    resolution: 0.02                # 2cm por pixel - boa resolução
    max_laser_range: 30.0           # 30m - alcance máximo do RPLidar S2
    min_laser_range: 0.05           # 5cm - SENSOR DE PROXIMIDADE (não ignorar < 15cm)
    minimum_time_interval: 0.05     # 50ms - atualização rápida
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000
    enable_interactive_mode: true
    use_response_expansion: true

    # === SCAN MATCHING SUAVE PARA MAPEAMENTO ESTÁVEL ===
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2    # 20cm - MENOS agressivo para mapeamento estável
    minimum_travel_heading: 0.2     # ~11° - MENOS agressivo
    scan_buffer_size: 10            # Buffer menor para menos correções bruscas
    scan_buffer_maximum_scan_distance: 20.0  # Limitado para mapeamento local
    link_match_minimum_response_fine: 0.5    # Mais conservador para evitar correções erradas
    link_scan_maximum_distance: 0.5          # Correções locais MENOS agressivas
    loop_search_maximum_distance: 1.0        # Loop closure MUITO restritivo
    do_loop_closing: false                   # ❌ DESABILITADO durante mapeamento inicial
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 0.8
    loop_match_minimum_response_coarse: 0.5
    loop_match_minimum_response_fine: 0.5

    # === PARÂMETROS DE CORRELAÇÃO PARA RPLIDAR S2 ===
    correlation_search_space_dimension: 0.5  # Área de busca normal
    correlation_search_space_resolution: 0.01  # Alta precisão
    correlation_search_space_smear_deviation: 0.1  # Baixa tolerância

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # === PENALIDADES NORMAIS PARA RPLIDAR S2 ===
    distance_variance_penalty: 0.5      # Penalidade baixa - confia no RPLidar S2
    angle_variance_penalty: 1.0         # Penalidade normal    

    fine_search_angle_offset: 0.00349     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0349        
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
